### ISSUE TITLE
[Log] long list of json not found

### ISSUE THREAD

**Issue by drakray** [grim3212/grim-pack#35]
http://pastebin.com/nLAFMTu2
don't seems critical, just annoying in the log

**Comment by grim3212** [comment]
Hmm, again very strange. I am unable to replicate this and all the models look fine to me.
Are any of those models broken?
What version of Forge are you using?

**Comment by drakray** [comment]
2085, everything seems fine, but I use a resourcePack, Faithful x32, could it be that?

**Comment by drakray** [comment]
I tried no resPack, no other mod, Grim 24, Forge 2085, and I got it
New map, Creative, Superflat Void, which generate Bedrock strangely
[Start line 362](http://pastebin.com/UjEZD2rj)

**Comment by drakray** [comment]
The Bedrock issue seems to come from Grimpack too, as I get it with Grimpack alone, but not Vanilla/Forge alone

**Comment by grim3212** [comment]
Hahaha find all kinds of problems. So, those are on the actual FML logs, not the console's thats why I thought there might be model errors. I assume that other mods that take advantage of forge blockstates generate the same messages. To get rid of them I would basically need to make a dummy json for everyone of those when the Forge blockstate is supposed to save some time and make it so that we don't need as many different jsons. 

So I probably will leave it alone because I can't think of any easy way to get around it. Sorry

Also, I will look into the bedrock thing.
