### ISSUE TITLE
[suggestion] New Blocks and Items

### ISSUE THREAD

**Issue by Chunkimunki** [grim3212/grim-pack#61]
Any thoughts on a these for the pack? Your genius knows no bounds so here goes..
1) Flashlight - Either/or 
  Passive function ie toggle flashlight on/off
                             or
  Actual held item which may or may not use a charge and can be used in off hand.
  There's no such item as far as I can tell for 1.10.2 and although dynamic lighting apparently a swine
   they managed it in 1.7.10 !?
   Just think - Hardcore Darkness and your flashlight spot illuminating that lurking mob! Awesome!

2) Ghost blocks that are invisible/pass through until illuminated with item ie flashlight.
    Different coloured blocks showing with different coloured lenses/filters perhaps.
    Groovey..

3) Scan cards and lock blocks for your doors etc. Nice.

4) An alarm block activated by your fab new sensor! Different sounds for different levels of heart attack!

5) Timer/countdown block - adjustable count just to make getting through a togglerack floor space
     that much more interesting.

6) Target block - activated redstone signal by projectile hit - Bullseye leads the way!

7) Sound Dampening block - adjustable area to hide that zombie in the closet!

8) Silent camo pressure plates - for those that don't want to use sensors (crazy people).

9) Ropes/chains you can climb - possible coils that come down when thrown/fired at blocks above
    Grappling gun/harpoon kinda thing.

10) Hand held sensor/scanner to detect mobs - "Aliens" are go! 

11) A Grappling Hook which has two functions activated in config - a) any block works as an anchor
      b) specific (new?) blocks can only be targeted/used and place player on top of block (map building)

12) Scalable Climbing blocks used to get player to top/roof of structures

13) Slo-mo block - set client tick rate at low for specific time before returning back to normal - great for
      'hold breath' parkour jumps

Phew - hope these ideas get your creative juices flowing.. or not! lol

**Comment by grim3212** [comment]
Alright so the I'll list my thoughts for each.
1. I like the idea but I don't know exactly how I would get around this. As far as I know most people just placed invisible blocks with light sources to fake this but that can sometimes be really expensive. Another way is to only have it client side but I think it would be fun to explore things in the dark with friends.
2. Possible if I could get the flashlights working but I a do not know.
3. I like this idea and might implement it.
4. Another cool idea but the reason I went for the sensor that I did was because I didn't want to deal with wireless transmission for using multiple blocks, which this would most likely require.
5. Also, like this idea.
6. Actually already working on this 😄 
7. I don't know about this one since there is already that one from OpenBlocks and they might end up updating.
8. I like this idea and would be relatively simple
9. Another cool idea
10. Not sure what you mean for this? Would it just tell you what it is?
11. Maybe but I know that there are other Grappling Hooks from other mods.
12. Like new ladders?
13. Least likely because I try to make everything work on multiplayer which that could cause a lot of problems. But, I did have something like that before. [TimeControl](http://mods.grim3212.com/mc/individual-mods/time-control/) Lots of broken images but has remotes for what you are talking about.

So, a lot of these are cool but I don't know when or if I will get around to them. I have a lot of people giving me ideas and not a lot of time to work on them.

**Comment by grim3212** [comment]
Closing as GrimPack is no longer maintained.
