### ISSUE TITLE
Crash compatibility with D3Core materials.json

### ISSUE THREAD

**Issue by drakray** [grim3212/grim-pack#83]
http://pastebin.com/iqhra5G6
Crash when trying to use a d3core/materials.json file to set missing repair material

**Comment by grim3212** [comment]
So I think this is because I have already set the repair material. There was a bug in D3Core that got fixed but I don't think it is in the latest release.

https://github.com/DoubleDoorDevelopment/D3Core/commit/5503e612356156d4a17f4eb02f39c60239e1e023

EDIT: Okay never mind looks like it is in the latest release. I am not sure why this is breaking things though.

**Comment by drakray** [comment]
The materials I'm adding are for Botania though, so I think it's a compatibility issue in the way things work

**Comment by grim3212** [comment]
I think I might know what is going on... What does your materials.json look like?

EDIT: Should be fixed now

**Comment by drakray** [comment]
http://pastebin.com/y3SxuSHR

**Comment by grim3212** [comment]
Did the latest version fix that at least?

**Comment by drakray** [comment]
Yes, that is fixed in the 4.0.0.2 version (now steel lumberaxe seems buggy, but it may be because BetterwithMods add steel axe too, so i'll check with Lumberaxe(which use d3core/materials.json))
